### PR TITLE
Created end to end system test for Google Calendar sync

### PR DESCRIPTION
**Pull request by ctaylor451**

### CODE REVIEW

**Comment by andyl** [comment]
Couple of things:

1) CI failed - I suspect TravisCI doesn't allow you to pull data from 3rd party servers.  

2) The old tests ran in less than a second.  The new tests take longer (10 seconds?).  

Recommendations:
- create three rake tasks: 
  > rake spec - runs all specs
  > rake spec:unit - runs 'lib' and 'rake' specs (fast)
  > rake spec:system - runs 'system' specs (slow)
- adjust guard so it runs 'rake spec:unit'
- adjust CI so it runs 'rake spec:unit'

Let me know if you're OK with these recommendations.  If so, let me know if you'd like me to make the change (I can do it fast), or if you would like to do it.

**Comment by ctaylor451** [comment]
All sounds reasonable.  Having a smoke test vs full system test is a good
idea.  I'd leave the default rake with no args as a full test (rake spec)
so we run in more often.
Not sure what you mean by guard
CI runs smoke tests (unit tests for now)

If you can do it quickly please do, I'm out of the code base for today --
unless you need something from me

**Comment by andyl** [comment]
I made the changes.

On Wed, Jan 6, 2016 at 2:00 PM, Craig Taylor <notifications@github.com>
wrote:

> All sounds reasonable. Having a smoke test vs full system test is a good
> idea. I'd leave the default rake with no args as a full test (rake spec)
> so we run in more often.
> Not sure what you mean by guard
> CI runs smoke tests (unit tests for now)
>
> If you can do it quickly please do, I'm out of the code base for today --
> unless you need something from me
>
> On Wed, Jan 6, 2016 at 1:17 PM andyl <notifications@github.com> wrote:
>
> > Couple of things:
> >
> > 1) CI failed - I suspect TravisCI doesn't allow you to pull data from 3rd
> > party servers.
> >
> > 2) The old tests ran in less than a second. The new tests take longer (10
> > seconds?).
> >
> > Recommendations:
> >
> > - create three rake tasks: > rake spec - runs all specs > rake
> > spec:unit - runs 'lib' and 'rake' specs (fast) > rake spec:system - runs
> > 'system' specs (slow)
> > - adjust guard so it runs 'rake spec:unit'
> > - adjust CI so it runs 'rake spec:unit'
> >
> > Let me know if you're OK with these recommendations. If so, let me know
> if
> > you'd like me to make the change (I can do it fast), or if you would like
> > to do it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/andyl/BAMRU-Org/pull/20#issuecomment-169464050>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andyl/BAMRU-Org/pull/20#issuecomment-169476219>.
>



-- 
andy@r210.com
650-823-0836

**Comment by ctaylor451** [comment]
Brief testing, everything seems to work.  Do we want the default to be
:unit?  Seems like :all is a better default, running more tests is better
unless you are intentionally limiting the time (eq, CI)

**Comment by ctaylor451** [comment]
What do the load lines do in the Rakefile?  They seem unnecessary, can I
remove them?  Having to maintain a file list of files in the spec directory
doesn't seem to have value

load "./lib/rake/dev.rake" load "./lib/rake/site.rake" load
"./lib/rake/data.rake" load "./lib/rake/spec.rake" load
"./lib/rake/crondev.rake" load "./lib/rake/total.rake" load
"./lib/rake/admin.rake"

**Comment by andyl** [comment]
Default has to be unit, because the system specs fail on CI (I'm not sure
why)

On Wed, Jan 6, 2016 at 4:43 PM, Craig Taylor <notifications@github.com>
wrote:

> Brief testing, everything seems to work. Do we want the default to be
> :unit? Seems like :all is a better default, running more tests is better
> unless you are intentionally limiting the time (eq, CI)
>
>
> On Wed, Jan 6, 2016 at 4:03 PM andyl <notifications@github.com> wrote:
>
> > I made the changes.
> >
> > On Wed, Jan 6, 2016 at 2:00 PM, Craig Taylor <notifications@github.com>
> > wrote:
> >
> > > All sounds reasonable. Having a smoke test vs full system test is a
> good
> > > idea. I'd leave the default rake with no args as a full test (rake
> spec)
> > > so we run in more often.
> > > Not sure what you mean by guard
> > > CI runs smoke tests (unit tests for now)
> > >
> > > If you can do it quickly please do, I'm out of the code base for today
> --
> > > unless you need something from me
> > >
> > > On Wed, Jan 6, 2016 at 1:17 PM andyl <notifications@github.com> wrote:
> > >
> > > > Couple of things:
> > > >
> > > > 1) CI failed - I suspect TravisCI doesn't allow you to pull data from
> > 3rd
> > > > party servers.
> > > >
> > > > 2) The old tests ran in less than a second. The new tests take longer
> > (10
> > > > seconds?).
> > > >
> > > > Recommendations:
> > > >
> > > > - create three rake tasks: > rake spec - runs all specs > rake
> > > > spec:unit - runs 'lib' and 'rake' specs (fast) > rake spec:system -
> > runs
> > > > 'system' specs (slow)
> > > > - adjust guard so it runs 'rake spec:unit'
> > > > - adjust CI so it runs 'rake spec:unit'
> > > >
> > > > Let me know if you're OK with these recommendations. If so, let me
> know
> > > if
> > > > you'd like me to make the change (I can do it fast), or if you would
> > like
> > > > to do it.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/andyl/BAMRU-Org/pull/20#issuecomment-169464050>.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/andyl/BAMRU-Org/pull/20#issuecomment-169476219>.
> > >
> >
> >
> >
> > --
> > andy@r210.com
> > 650-823-0836
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/andyl/BAMRU-Org/pull/20#issuecomment-169504055>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andyl/BAMRU-Org/pull/20#issuecomment-169510694>.
>



-- 
andy@r210.com
650-823-0836

**Comment by ctaylor451** [comment]
Does CI call rake without parameters?

**Comment by andyl** [comment]
it does now.  there is probably a way to configure it.

On Wed, Jan 6, 2016 at 5:30 PM, Craig Taylor <notifications@github.com>
wrote:

> Does CI call rake without parameters?
>
>
> On Wed, Jan 6, 2016 at 5:27 PM andyl <notifications@github.com> wrote:
>
> > Default has to be unit, because the system specs fail on CI (I'm not sure
> > why)
> >
> > On Wed, Jan 6, 2016 at 4:43 PM, Craig Taylor <notifications@github.com>
> > wrote:
> >
> > > Brief testing, everything seems to work. Do we want the default to be
> > > :unit? Seems like :all is a better default, running more tests is
> better
> > > unless you are intentionally limiting the time (eq, CI)
> > >
> > >
> > > On Wed, Jan 6, 2016 at 4:03 PM andyl <notifications@github.com> wrote:
> > >
> > > > I made the changes.
> > > >
> > > > On Wed, Jan 6, 2016 at 2:00 PM, Craig Taylor <
> notifications@github.com
> > >
> > > > wrote:
> > > >
> > > > > All sounds reasonable. Having a smoke test vs full system test is a
> > > good
> > > > > idea. I'd leave the default rake with no args as a full test (rake
> > > spec)
> > > > > so we run in more often.
> > > > > Not sure what you mean by guard
> > > > > CI runs smoke tests (unit tests for now)
> > > > >
> > > > > If you can do it quickly please do, I'm out of the code base for
> > today
> > > --
> > > > > unless you need something from me
> > > > >
> > > > > On Wed, Jan 6, 2016 at 1:17 PM andyl <notifications@github.com>
> > wrote:
> > > > >
> > > > > > Couple of things:
> > > > > >
> > > > > > 1) CI failed - I suspect TravisCI doesn't allow you to pull data
> > from
> > > > 3rd
> > > > > > party servers.
> > > > > >
> > > > > > 2) The old tests ran in less than a second. The new tests take
> > longer
> > > > (10
> > > > > > seconds?).
> > > > > >
> > > > > > Recommendations:
> > > > > >
> > > > > > - create three rake tasks: > rake spec - runs all specs > rake
> > > > > > spec:unit - runs 'lib' and 'rake' specs (fast) > rake
> spec:system -
> > > > runs
> > > > > > 'system' specs (slow)
> > > > > > - adjust guard so it runs 'rake spec:unit'
> > > > > > - adjust CI so it runs 'rake spec:unit'
> > > > > >
> > > > > > Let me know if you're OK with these recommendations. If so, let
> me
> > > know
> > > > > if
> > > > > > you'd like me to make the change (I can do it fast), or if you
> > would
> > > > like
> > > > > > to do it.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> https://github.com/andyl/BAMRU-Org/pull/20#issuecomment-169464050
> > >.
> > > > >
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/andyl/BAMRU-Org/pull/20#issuecomment-169476219
> >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > andy@r210.com
> > > > 650-823-0836
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/andyl/BAMRU-Org/pull/20#issuecomment-169504055>.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/andyl/BAMRU-Org/pull/20#issuecomment-169510694>.
> > >
> >
> >
> >
> > --
> > andy@r210.com
> > 650-823-0836
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/andyl/BAMRU-Org/pull/20#issuecomment-169517551>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andyl/BAMRU-Org/pull/20#issuecomment-169517984>.
>



-- 
andy@r210.com
650-823-0836

**Pull request merged**
